// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function EnsureRPortable() {
  return window['go']['main']['App']['EnsureRPortable']();
}

export function InstallCollections(arg1) {
  return window['go']['main']['App']['InstallCollections'](arg1);
}

export function OpenTrama() {
  return window['go']['main']['App']['OpenTrama']();
}
