// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {envcheck} from '../models';

export function CheckEnvironment():Promise<envcheck.EnvStatus>;

export function EnsureRPortable():Promise<void>;

export function InstallCollections(arg1:Array<string>):Promise<void>;

export function OpenTrama():Promise<void>;
