# Pressupostos e referências: escolha de hiperparâmetros e avaliação.

.tr_ml_docs_avaliacao <- function() {
  P <- .tr_ml_P; I <- .tr_ml_impl; R <- trama::tr_ref
  L <- .tr_ml_livros(); C <- .tr_ml_comuns()
  teste_fora <- P("As linhas avaliadas são do **teste**, que não participou do ajuste nem da escolha de hiperparâmetros. Previsões do treino marcado pelo `ml/split` são recusadas, salvo `permitir_treino` (que acrescenta a nota de otimismo); tabelas sem essa marca (divisão feita por fora, treino e teste juntados) são medidas como chegam, e num teste já usado para decidir a medida também sai otimista — isso nenhuma marca detecta.",
    se_falhar = "Avalie a saída teste do `ml/split` passada pelo `ml/predict`; se o teste já foi usado para escolher, separe um novo teste ou reporte a estimativa como otimista.")
  desequilibrio <- P("Com **classes desequilibradas**, a acurácia engana: prever sempre a classe maioritária já a deixa alta. A acurácia balanceada e o macro F1 dão peso igual a cada classe.",
    verificar = "data/group_summarise",
    se_falhar = "Conte as linhas por classe no `data/group_summarise` e leia a `balanced_accuracy` ou o `macro_f1` e a `ml/confusion`, não só a `accuracy`.")
  fawcett <- R(autores = "Fawcett, T.", ano = 2006, titulo = "An introduction to ROC analysis",
               fonte = "Pattern Recognition Letters, 27(8), 861-874", doi = "10.1016/j.patrec.2005.10.010")
  brodersen <- R(autores = c("Brodersen, K. H.", "Ong, C. S.", "Stephan, K. E.", "Buhmann, J. M."), ano = 2010,
                 titulo = "The Balanced Accuracy and Its Posterior Distribution",
                 fonte = "20th International Conference on Pattern Recognition (ICPR), 3121-3124",
                 doi = "10.1109/ICPR.2010.764", papel = "complementar")
  list(
    "ml/tune" = list(
      pressupostos = list(
        P("Entra **só o treino**: os folds saem das linhas recebidas e o vencedor é reajustado nelas todas. Se o teste entrar aqui, ele deixa de ser teste — a saída teste do `ml/split` é recusada (`tr_ml_error_test_leak`); uma divisão feita por fora não tem marca e depende de você.",
          se_falhar = "Ligue a saída treino do `ml/split`; a teste vai só ao `ml/predict`."),
        C$sem_vazamento,
        P("Os folds refletem a **dependência** dos dados: `aleatoria` (estratificada pela classe) supõe linhas independentes; `grupo` põe cada indivíduo, lote ou área num só fold; `temporal` usa origem móvel com janela crescente — cada fold treina no passado e valida no bloco seguinte, nunca no futuro do treino. Folds aleatórios com dados dependentes dão erro otimista (Roberts et al. 2017).",
          se_falhar = "Escolha `estrategia = \"grupo\"` com `grupo`, ou `\"temporal\"` com `ordem`, e use a mesma estratégia no `ml/split`."),
        P("A **média dos folds do vencedor é otimista**: foi a melhor entre muitas tentativas, e parte da vantagem é sorte. Ela serve para escolher, não para reportar o desempenho.",
          verificar = "ml/tuning_plot",
          se_falhar = "Reporte o desempenho medido no teste com `ml/predict` e `ml/evaluate`. Sem teste separado (n pequeno), use o `ml/nested_cv`, que estima o procedimento inteiro sem reaproveitar as linhas da escolha."),
        P("A **métrica** escolhida é a que importa no problema; `auto` usa RMSE (regressão) e macro F1 (classificação).",
          verificar = "data/group_summarise",
          se_falhar = "Com classes desequilibradas, prefira `balanced_accuracy` ou `macro_f1` a `accuracy`."),
        P("As **tentativas bastam** para o espaço de busca (busca aleatória): se o melhor ainda melhora perto do fim, o orçamento foi curto.",
          verificar = "ml/tuning_plot",
          se_falhar = "Aumente `tentativas` ou mude a `amplitude`."),
        C$semente),
      referencias = list(
        R(autores = "Stone, M.", ano = 1974, titulo = "Cross-Validatory Choice and Assessment of Statistical Predictions",
          fonte = "Journal of the Royal Statistical Society. Series B, 36(2), 111-133",
          doi = "10.1111/j.2517-6161.1974.tb00994.x"),
        R(autores = c("Bergstra, J.", "Bengio, Y."), ano = 2012, titulo = "Random Search for Hyper-Parameter Optimization",
          fonte = "Journal of Machine Learning Research, 13, 281-305",
          url = "https://www.jmlr.org/papers/v13/bergstra12a.html"),
        L$islr, L$kuhn, L$roberts, L$tashman, L$fpp3, L$bergmeir18,
        R(autores = c("Varma, S.", "Simon, R."), ano = 2006,
          titulo = "Bias in error estimation when using cross-validation for model selection",
          fonte = "BMC Bioinformatics, 7, 91", doi = "10.1186/1471-2105-7-91", papel = "complementar"),
        I("trama.ml", "tr_ml_tune", "Implementação própria: busca aleatória (log-uniforme para `cost`, `gamma` e `eta`) avaliada nos mesmos k folds (aleatórios estratificados, por grupo ou de origem móvel no tempo); o vencedor, pela média, é reajustado com `tr_ml_fit` em todas as linhas."))),

    "ml/nested_cv" = list(
      pressupostos = list(
        P("A estimativa é do **procedimento de ajuste inteiro** (busca + reajuste), não de um modelo final específico: cada fold externo escolhe hiperparâmetros próprios, e o vencedor pode mudar de fold para fold.",
          se_falhar = "Para o modelo a usar, rode o `ml/tune` em todas as linhas; reporte a média `externa` do `ml/nested_cv` como o desempenho esperado desse procedimento."),
        P("Só a coluna **`externa`** é honesta: mede linhas que a busca nunca viu. A `interna` é a média dos folds do vencedor dentro da busca e sai otimista (Varma & Simon 2006); a diferença entre elas mostra o otimismo da seleção.",
          se_falhar = "Não reporte a `interna`; se ela ficar muito acima da `externa`, a busca está escolhendo ruído — reduza o espaço ou as tentativas."),
        P("Os folds externos e internos seguem a mesma **estratégia** (`aleatoria`, `grupo` ou `temporal`) e supõem a mesma estrutura de dependência do `ml/tune`.",
          se_falhar = "Com tempo ou grupos, escolha `estrategia = \"temporal\"` (com `ordem`) ou `\"grupo\"` (com `grupo`)."),
        P("Com poucas linhas, cada busca interna vê só uma parte do treino: a estimativa externa é **pessimista e variável** (poucas linhas por fold), e o custo é folds externos × tentativas × folds internos ajustes.",
          se_falhar = "Leia a variação entre folds; aumente `folds_externos` só se houver linhas para isso."),
        C$semente),
      referencias = list(
        R(autores = c("Varma, S.", "Simon, R."), ano = 2006,
          titulo = "Bias in error estimation when using cross-validation for model selection",
          fonte = "BMC Bioinformatics, 7, 91", doi = "10.1186/1471-2105-7-91"),
        R(autores = c("Cawley, G. C.", "Talbot, N. L. C."), ano = 2010,
          titulo = "On over-fitting in model selection and subsequent selection bias in performance evaluation",
          fonte = "Journal of Machine Learning Research, 11, 2079-2107",
          url = "https://www.jmlr.org/papers/v11/cawley10a.html", papel = "complementar"),
        L$islr, L$kuhn,
        I("trama.ml", "tr_ml_nested_cv", "Implementação própria: folds externos formados como no `ml/tune`; em cada um, `tr_ml_tune` completo só no treino externo e a métrica do vencedor na validação externa."))),

    "ml/split" = list(
      pressupostos = list(
        P("A **estratégia de divisão** respeita a dependência entre linhas: `aleatoria` supõe linhas independentes; com medidas no tempo o teste deve ser todo posterior ao treino (`temporal`), e com várias linhas do mesmo indivíduo, lote ou área nenhum grupo pode cair dos dois lados (`grupo`). Senão o teste mede memorização, não generalização (Roberts et al. 2017).",
          se_falhar = "Troque `estrategia` para `temporal` (com `ordem`) ou `grupo` (com `grupo`) e use a mesma no `ml/tune`."),
        P("Na divisão `temporal`, o teste representa o **futuro em que o modelo será usado**: o corte no tempo cai onde a proporção pede, com instantes empatados todos do mesmo lado.",
          se_falhar = "Se houver mudança de regime depois do corte, o teste mede também essa mudança; leia o desempenho junto do período."),
        P("Na divisão `grupo`, `proporcao` é a **fração dos grupos**; com grupos de tamanhos muito diferentes, a fração das linhas pode se afastar dela, e a estratificação por classe não é feita.",
          verificar = "data/group_summarise",
          se_falhar = "Conte linhas e classes por lado no `data/group_summarise`; se uma classe faltar no teste, mude a semente ou a proporção."),
        P("As saídas levam a **proveniência** (atributo `tr_ml_origem`: papel treino/teste, um id da divisão e as impressões digitais das linhas do teste, com a contagem de cópias): ajustar no teste, ou numa tabela que junta treino e teste, é recusado; prever o teste com um modelo que viu linhas dele no ajuste é recusado; avaliar o treino, ou um teste misturado a linhas de fora, exige `permitir_treino` — o vazamento treino-teste de Kaufman et al. (2012) barrado por construção. A marca sobrevive ao cache, a filtros e a colunas novas.",
          se_falhar = "Faça a divisão sempre no `ml/split`, antes de qualquer escolha."),
        P("A marca **não cobre**: juntar com o teste à direita (`data/join` com o teste como segunda tabela), remodelar (`pivot_longer`/`pivot_wider`), recriar a tabela à mão, reescrever ou tirar colunas da divisão, e dividir fora do `ml/split`. Nesses casos os blocos seguem como sem marca.",
          se_falhar = "Divida primeiro e transforme cada lado depois; se precisar de uma dessas operações, mantenha o teste longe dos ajustes você mesmo."),
        C$semente),
      referencias = list(L$kaufman, L$roberts, L$tashman, L$fpp3, L$islr, L$kuhn,
        I("trama.ml", "tr_ml_split", "Implementação própria: sorteio estratificado pela classe (`aleatoria`); corte no instante da linha floor(n·proporção) na ordem do tempo, todas as linhas até ele no treino (`temporal`); sorteio de floor(G·proporção) grupos inteiros (`grupo`)."))),

    "ml/evaluate" = list(
      pressupostos = list(teste_fora, desequilibrio,
        P("Na regressão, o **R²** compara com a média do próprio conjunto avaliado; no teste pode ser negativo (pior que prever a média) e é indefinido com resposta constante.",
          verificar = "ml/residuals",
          se_falhar = "Leia RMSE e MAE, na unidade da resposta, junto do gráfico de resíduos."),
        P("O **kappa** desconta a concordância esperada pelas marginais, mas depende da prevalência: com uma classe muito rara ele cai mesmo com boa acurácia, e não há escala universal do que é “bom”.",
          se_falhar = "Leia o kappa junto da acurácia balanceada e das métricas por classe."),
        P("Precisão, revocação e F1 **por classe** tratam cada classe contra as demais; com poucas linhas de uma classe (coluna `n`), os valores dela variam muito. Uma classe nunca prevista tem precisão 0 por convenção.",
          verificar = "ml/confusion",
          se_falhar = "Confira as contagens na `ml/confusion` antes de interpretar a classe."),
        P("A medida vem de **um único teste**: com poucas linhas ela varia muito de uma divisão para outra.",
          se_falhar = "Refaça o `ml/split` com outras sementes e compare; ou use o `ml/tune`, que mostra a variação entre folds.")),
      referencias = list(L$islr, L$kuhn, brodersen,
        R(autores = "Cohen, J.", ano = 1960, titulo = "A Coefficient of Agreement for Nominal Scales",
          fonte = "Educational and Psychological Measurement, 20(1), 37-46", doi = "10.1177/001316446002000104"),
        R(autores = c("Sokolova, M.", "Lapalme, G."), ano = 2009,
          titulo = "A systematic analysis of performance measures for classification tasks",
          fonte = "Information Processing & Management, 45(4), 427-437", doi = "10.1016/j.ipm.2009.03.002",
          papel = "complementar"),
        I("trama.ml", "tr_ml_evaluate", "Cálculo próprio: MAE, RMSE e R² = 1 − SQE/SQT; na classificação, por classe (um contra todos) precisão, revocação e F1, com médias macro sobre as classes observadas no alvo e ponderadas pelo suporte; acurácia balanceada = média das revocações; kappa = (po − pe)/(1 − pe) com pe das marginais. Conferido contra `yardstick` (macro, macro_weighted, kap). Nenhuma linha é descartada."))),

    "ml/confusion" = list(
      pressupostos = list(teste_fora, desequilibrio,
        P("Observado e previsto usam os **mesmos rótulos** de classe; um rótulo escrito diferente vira uma classe a mais.",
          se_falhar = "Padronize os rótulos com o `data/mutate` antes.")),
      referencias = list(fawcett, L$islr, L$kuhn,
        I("trama.ml", "tr_ml_confusion", "Cálculo próprio com `base::table`, sobre a união das classes observadas e previstas, incluindo as contagens zero."))),

    "ml/pr_curve" = list(
      pressupostos = list(teste_fora,
        P("**Duas classes**, e a coluna de probabilidade é a **da classe positiva** — a classe de interesse, em geral a rara. Com `positiva` vazia a classe vem do nome da coluna (`.prob_<classe>`); com coluna de nome livre o bloco pede `positiva`.",
          se_falhar = "Preencha `positiva` com a classe cuja probabilidade a coluna contém."),
        P("A referência do acaso é a **prevalência** da classe positiva, não 0,5: a AP só diz algo comparada a ela, e a curva de um conjunto com outra prevalência não é comparável (Saito & Rehmsmeier 2015).",
          verificar = "data/group_summarise",
          se_falhar = "Compare modelos no mesmo teste; para comparar populações diferentes, leia a ROC."),
        P("A **AP** (soma de ganho de revocação × precisão) e a **área interpolada** de Davis & Goadrich são estimativas diferentes da mesma área; ligar os pontos por reta superestima a área e não é usado (Davis & Goadrich 2006).",
          se_falhar = "Reporte uma delas nomeada; a AP é a do `yardstick` e do scikit-learn, a área é a do `PRROC`."),
        P("Com **poucos positivos** a curva tem poucos degraus e a AP varia muito de um teste para outro.",
          se_falhar = "Leia a quantidade de positivos (`prevalencia` × n) e repita a divisão com outras sementes.")),
      referencias = list(
        R(autores = c("Saito, T.", "Rehmsmeier, M."), ano = 2015,
          titulo = "The Precision-Recall Plot Is More Informative than the ROC Plot When Evaluating Binary Classifiers on Imbalanced Datasets",
          fonte = "PLOS ONE, 10(3), e0118432", doi = "10.1371/journal.pone.0118432"),
        R(autores = c("Davis, J.", "Goadrich, M."), ano = 2006,
          titulo = "The relationship between Precision-Recall and ROC curves",
          fonte = "Proceedings of the 23rd International Conference on Machine Learning (ICML), 233-240",
          doi = "10.1145/1143844.1143874"),
        R(autores = c("Keilwagen, J.", "Grosse, I.", "Grau, J."), ano = 2014,
          titulo = "Area under Precision-Recall Curves for Weighted and Unweighted Data",
          fonte = "PLoS ONE, 9(3), e92209", doi = "10.1371/journal.pone.0092209", papel = "complementar"),
        R(autores = c("Su, W.", "Yuan, Y.", "Zhu, M."), ano = 2015,
          titulo = "A Relationship between the Average Precision and the Area Under the ROC Curve",
          fonte = "Proceedings of the 2015 International Conference on the Theory of Information Retrieval (ICTIR), 349-352",
          doi = "10.1145/2808194.2809481", papel = "complementar"),
        I("trama.ml", "tr_ml_pr_curve", "Cálculo próprio: um ponto por limiar distinto (empates num degrau); AP = Σ ΔR·P; área com a interpolação de Davis & Goadrich integrada em forma fechada. Conferido contra `yardstick::average_precision` e `PRROC::pr.curve` (`auc.integral`)."))),

    "ml/roc" = list(
      pressupostos = list(teste_fora,
        P("**Duas classes**, e a coluna de probabilidade é a **da classe positiva**. Com `positiva` vazia o bloco deduz a classe do nome da coluna (`.prob_<classe>`); se o nome não indicar uma classe observada, o bloco recusa e pede `positiva`. Se classe e coluna não baterem, a curva sai espelhada (AUC = 1 − AUC).",
          se_falhar = "Com uma coluna de nome livre, preencha `positiva` com a classe cuja probabilidade ela contém."),
        P("A AUC resume **todos os cortes**, inclusive os que ninguém usaria, e não muda com o desequilíbrio das classes — por isso mesmo pode parecer boa quando a classe rara é mal prevista.",
          verificar = c("ml/confusion", "data/group_summarise"),
          se_falhar = "Leia junto a matriz de confusão, a acurácia balanceada no `ml/evaluate` e, com classe rara, a `ml/pr_curve`."),
        P("O **intervalo de DeLong** é assintótico (normal): com poucos positivos ou negativos, ou AUC perto de 1, ele fica estreito demais e é truncado em [0, 1]. Com AUC = 0 ou 1 a variância de DeLong é zero: o intervalo sai **indisponível** (NA), com a nota em `auc_nota`, em vez de um falso intervalo de largura zero.",
          se_falhar = "Com poucas linhas, leia o intervalo como aproximado e repita a divisão com outras sementes."),
        P("O **corte de Youden** é escolhido nas mesmas linhas em que é lido: a sensibilidade e a especificidade nele são otimistas, e J pesa igualmente falso positivo e falso negativo, o que raramente reflete os custos reais.",
          se_falhar = "Escolha o corte num conjunto de validação (ou pelos custos do problema) e leia o desempenho dele no teste, com o `corte` do `ml/linear` ou a `ml/confusion`.")),
      referencias = list(
        R(autores = c("Hanley, J. A.", "McNeil, B. J."), ano = 1982,
          titulo = "The meaning and use of the area under a receiver operating characteristic (ROC) curve",
          fonte = "Radiology, 143(1), 29-36", doi = "10.1148/radiology.143.1.7063747"),
        fawcett, L$islr,
        R(autores = c("Saito, T.", "Rehmsmeier, M."), ano = 2015,
          titulo = "The Precision-Recall Plot Is More Informative than the ROC Plot When Evaluating Binary Classifiers on Imbalanced Datasets",
          fonte = "PLOS ONE, 10(3), e0118432", doi = "10.1371/journal.pone.0118432", papel = "complementar"),
        R(autores = c("DeLong, E. R.", "DeLong, D. M.", "Clarke-Pearson, D. L."), ano = 1988,
          titulo = "Comparing the Areas under Two or More Correlated Receiver Operating Characteristic Curves: A Nonparametric Approach",
          fonte = "Biometrics, 44(3), 837-845", doi = "10.2307/2531595"),
        R(autores = "Youden, W. J.", ano = 1950, titulo = "Index for rating diagnostic tests",
          fonte = "Cancer, 3(1), 32-35", doi = "10.1002/1097-0142(1950)3:1<32::AID-CNCR2820030106>3.0.CO;2-3"),
        R(autores = c("Robin, X.", "Turck, N.", "Hainard, A.", "Tiberti, N.", "Lisacek, F.", "Sanchez, J.-C.", "Müller, M."),
          ano = 2011, titulo = "pROC: an open-source package for R and S+ to analyze and compare ROC curves",
          fonte = "BMC Bioinformatics, 12, 77", doi = "10.1186/1471-2105-12-77", papel = "complementar"),
        I("trama.ml", "tr_ml_roc", "Cálculo próprio: ordena pela probabilidade, agrupa empates num só degrau e integra a AUC pela regra do trapézio; IC de DeLong pelos componentes estruturais (intervalo normal truncado em [0, 1]); corte de Youden = máximo de sensibilidade + especificidade − 1 (empate: maior limiar). Conferido contra `pROC`.")))
  )
}
