test_that("AAS: n exato, pesos N/n, e a semente reproduz sem mexer na do usuário", {
  f <- ex("fazendas")
  set.seed(42); antes <- .Random.seed
  a <- tr_sampling_srs(f, n = 150L, .seed = 7L)
  expect_identical(.Random.seed, antes)
  b <- tr_sampling_srs(f, n = 150L, .seed = 7L)
  expect_identical(a$dados$fazenda, b$dados$fazenda)
  expect_false(identical(a$dados$fazenda, tr_sampling_srs(f, n = 150L, .seed = 8L)$dados$fazenda))
  expect_equal(nrow(a$dados), 150L)
  expect_false(anyDuplicated(a$dados$fazenda) > 0)
  expect_equal(unique(a$dados$peso_amostral), 2400 / 150)
  expect_equal(nrow(tr_sampling_srs(f, fracao = 0.05)$dados), 120L)
  expect_error(tr_sampling_srs(f), class = "tr_sampling_error_blank_param")
  expect_error(tr_sampling_srs(f, n = 3000L), class = "tr_sampling_error_too_large")
  expect_no_error(tr_sampling_srs(f[1:10, ], n = 30L, reposicao = TRUE))
})

test_that("sistemática dá n exato com intervalo fracionário e respeita a ordenação", {
  f <- ex("fazendas")
  s <- tr_sampling_systematic(f, n = 7L, ordenar = "area_ha", .seed = 2L)
  expect_equal(nrow(s$dados), 7L)
  expect_false(is.unsorted(s$dados$area_ha))
  expect_equal(nrow(tr_sampling_systematic(f[1:103, ], n = 10L)$dados), 10L)
})

test_that("estratificada: alocação, pesos N_h/n_h e plano que casa pelo nome", {
  f <- ex("fazendas")
  s <- tr_sampling_stratified(f, "regiao", n = 240L, .seed = 1L)
  expect_equal(as.integer(table(s$dados$regiao)[c("Norte", "Sul", "Leste", "Oeste")]), c(30L, 90L, 60L, 60L))
  expect_equal(sum(s$dados$peso_amostral), 2400)
  p <- tr_sampling_size_stratified(ex("estratos_fazendas"), "regiao", "N", "desvio_producao", erro = 60)
  sp <- tr_sampling_stratified(f, "regiao", plano = p)
  expect_equal(as.integer(table(sp$dados$regiao)[p$alocacao$estrato]), p$alocacao$n_final)
  f2 <- f; f2$regiao[f2$regiao == "Norte"] <- "Amazônia"
  expect_error(tr_sampling_stratified(f2, "regiao", plano = p), class = "tr_sampling_error_plan_mismatch")
  expect_error(tr_sampling_stratified(f, "regiao", plano = tr_sampling_size_proportion()),
               class = "tr_sampling_error_plan_mismatch")
  expect_error(tr_sampling_srs(f, plano = p), class = "tr_sampling_error_plan_mismatch")
  expect_error(tr_sampling_stratified(f, "Regiao", n = 100L), class = "tr_sampling_error_unknown_column")
  ney <- tr_sampling_stratified(f, "regiao", n = 240L, alocacao = "neyman", variavel_auxiliar = "producao_t")
  expect_gt(sum(ney$dados$regiao == "Norte"), 30L)
  expect_error(tr_sampling_stratified(f, "regiao", n = 240L, alocacao = "neyman"), class = "tr_sampling_error_blank_param")
})

test_that("PPS: probabilidades somam n, certezas entram, e o total é Horvitz-Thompson", {
  x <- c(100, 1, 2, 3, 4, 5, 6, 7, 8, 9)
  s <- .tr_sampling_pps_indices(x, 4L)
  expect_true(s$certeza[[1]])
  expect_equal(sum(s$pi), 4)
  expect_length(s$idx, 4L)
  expect_true(1L %in% s$idx)
  f <- ex("fazendas")
  a <- tr_sampling_pps(f, "area_ha", n = 100L, .seed = 3L)
  expect_equal(nrow(a$dados), 100L)
  expect_equal(tr_sampling_total(a, "producao_t")$tabela$estimativa, sum(a$dados$producao_t / a$dados$prob_inclusao))
  f$area_ha[[5]] <- 0
  expect_error(tr_sampling_pps(f, "area_ha", n = 10L), class = "tr_sampling_error_bad_size")
})

test_that("conglomerados em um e dois estágios", {
  f <- ex("fazendas")
  c1 <- tr_sampling_cluster(f, "municipio", conglomerados = 10L, .seed = 4L)
  expect_equal(length(unique(c1$dados$municipio)), 10L)
  expect_equal(nrow(c1$dados), 200L)
  expect_equal(unique(c1$dados$peso_amostral), 12)
  e <- ex("escolas")
  c2 <- tr_sampling_two_stage(e, "escola", conglomerados = 20L, por_conglomerado = 10L, .seed = 4L)
  expect_equal(nrow(c2$dados), 200L)
  # PPS no primeiro estágio com n_c fixo: autoponderada.
  expect_equal(diff(range(c2$dados$peso_amostral)), 0, tolerance = 1e-8)
  expect_equal(c2$dados$peso_amostral[[1]], nrow(e) / 200, tolerance = 1e-8)
  expect_error(tr_sampling_cluster(f, "municipio", conglomerados = 500L), class = "tr_sampling_error_too_large")
  expect_error(tr_sampling_cluster(f, "municipio", conglomerados = 1L), class = "tr_sampling_error_too_few")
  pl <- tr_sampling_size_cluster(tr_sampling_size_proportion(erro = 0.1), 10, 0.1, 200)
  c3 <- tr_sampling_two_stage(e, "escola", plano = pl)
  expect_equal(length(unique(c3$dados$escola)), pl$conglomerados)
  expect_error(tr_sampling_two_stage(e, "escola", conglomerados = 5L), class = "tr_sampling_error_blank_param")
})

test_that("desenho declarado e pós-estratificação", {
  d <- ex("domicilios")
  s <- tr_sampling_design(d, pesos = "peso", estrato = "estrato", conglomerado = "setor", populacao = "setores_estrato")
  expect_equal(s$desenho$fpc[["urbano"]], 400)
  expect_equal(length(unique(s$desenho$psu)), 42L)
  expect_error(tr_sampling_design(d, estrato = "estrato", conglomerado = "setor"), class = "tr_sampling_error_no_weights")
  sem_peso <- tr_sampling_design(d, estrato = "estrato", populacao = "setores_estrato")
  expect_equal(sum(sem_peso$dados$peso_amostral), 550)
  d2 <- d; d2$peso[[1]] <- 0
  expect_error(tr_sampling_design(d2, pesos = "peso"), class = "tr_sampling_error_bad_size")
  f <- ex("fazendas")
  a <- tr_sampling_srs(f, n = 200L, .seed = 5L)
  tot <- ex("estratos_fazendas")
  p <- tr_sampling_poststratify(a, tot, "regiao", "N")
  expect_equal(as.numeric(tapply(p$dados$peso_amostral, p$dados$regiao, sum)[tot$regiao]), tot$N)
  expect_length(p$receita$pos, 1L)
  expect_error(tr_sampling_poststratify(a, tot[-1, ], "regiao", "N"), class = "tr_sampling_error_missing_total")
  expect_error(.tr_sampling_refazer(s), class = "tr_sampling_error_no_population")
})
